### ISSUE TITLE
Update CI accounts

### ISSUE THREAD

**Issue by kayoub5** [dotpcap/sharppcap#350]
All CI accounts needs to be updated after the repo was moved to dotpcap.

**Comment by chmorgan** [comment]
@kayoub5 @PhyxionNL do you have an azure pipelines account and want access to the azure team? If you can give me your account info, name, email (I have no idea what I'll need to add you) I can rename the team from 'chmorgan' to 'dotpcap' and add you as admins to it. You don't have to post here you can email me at chmorgan@gmail.com with your info.

**Comment by kayoub5** [comment]
> I can rename the team from 'chmorgan' to 'dotpcap' 

Yeah, that would be good.

> You don't have to post here you can email me

Done.

**Comment by kayoub5** [comment]
@chmorgan AppVoyer needs to be updated as well.

**Comment by chmorgan** [comment]
@kayoub5 updated appveyor to the org address. Not sure if there is a way to get a team account for free there.

**Comment by PhyxionNL** [comment]
> @kayoub5 @PhyxionNL do you have an azure pipelines account and want access to the azure team? 

Sent 😊

**Comment by chmorgan** [comment]
@PhyxionNL added you to azure team. Closing ticket for now.
