### ISSUE TITLE
A device connected to the system does not work

### ISSUE THREAD

**Issue by Aaron2550** [dotpcap/sharppcap#351]
Hey, i keep getting the error "Can't send packet: send error: PacketSendPacket failed: A device connected to the system does not work. (31)" when trying to use `SendPacket(byte[], int)`. The Device does work tho, since im writing this Issue while using said Device. Im using SharpPcap 6.1.0 on Windows 10 21H1. Running the Program as Admin wont fix it either. Any Ideas?

**Comment by kayoub5** [comment]
@Aaron2550 
* What kind of device is it? physical ? virtual? Ethernet? WiFi? integrated card or USB Ethernet adapter?
* What's the device connected to?
* Does this error happen sporadically? or you can never get the device to work?
* Does the device sporadically disconnects and connects back again?

**Comment by Aaron2550** [comment]
Sorry for the wait!

- The Device is a Physical one, it calls itself a "Realtek PCIe GbE Family Controller", and came with my Mainboard
- The Device is connected to my LAN
- I can never get it to work
- No, the Device does not randomy disconnect.
- The packet i'm trying to send is 10792 bytes. *Now that you asked me this question, i realized this is probably wayyyy to big. I didn't check if what i captured came in multiple packets and just tried to send the whole block of data. I'm gonna try figuring out how to split the data i captured again and if that works i'll close this issue*

**Comment by kayoub5** [comment]
@Aaron2550 you are sending data larger than your adapter MTU (default 1500)
