### ISSUE TITLE
Anyone have experience reading data when using a gaming VPN like ExitLag?

### ISSUE THREAD

**Issue by Triky313** [dotpcap/sharppcap#379]
I haven't gotten it to work yet when a VPN like ExitLag is active.
Does anyone have an idea what I generally have to consider if I want to capture data and a VPN is active?

I run everything through NPCap.

**Comment by kayoub5** [comment]
VPN will create a virtual interface, you can normally see the traffic when capturing on that interface.

**Comment by Triky313** [comment]
This does not work with ExitLag. Other VPN providers have no problem. Apparently the problem is on ExitLag's side.
