### ISSUE TITLE
Optimize appveyor CI

### ISSUE THREAD

**Issue by kayoub5** [dotpcap/sharppcap#396]
So far the slowest CI we have is appveyor, it does not allow jobs to run in parallel

The hosts provided by appveyor are slow as well, it would reduce CI time a lot if we limit the scope of what appveyor run:

* Run only Windows and macos jobs, not Linux (Linux is covered enough by other CI providers)
* Run only PRs, not branches (currently appveyor runs twice for each commit in each PR)

@chmorgan thoughts?

**Comment by chmorgan** [comment]
I'm open to whatever you'd like to do on this front.

On a related topic, are we dropping support for circleci? I seem to recall this but perhaps that was for PacketDotNet instead.

**Comment by kayoub5** [comment]
We didn't drop circleci as far as I remember, the config files are still committed, it just stopped working (maybe when we switched the repo from your account to the dotpcap org) 

I don't have enough access right on the CI websites to figure out what's going on.

On a side note, having access to at least re-run jobs on appveyor will help with the sporadically failing tests.

**Comment by chmorgan** [comment]
Alright, created a team in the org on GitHub and granted the team user access to my appveyor account. If you wanted to make an org appveyor account that might be better but not sure if that’s possible with the free appveyor account.

let me know if you get a chance to see if that gives you permission to rerun ci jobs etc. I can adjust here if you need admin access.

**Comment by kayoub5** [comment]
> Alright, created a team in the org on GitHub and granted the team user access to my appveyor account. If you wanted to make an org appveyor account that might be better but not sure if that’s possible with the free appveyor account.
> 
> let me know if you get a chance to see if that gives you permission to rerun ci jobs etc. I can adjust here if you need admin access.

I don't see any changes in my access to appveyor, the sharpcap project does not even show up in https://ci.appveyor.com/projects for me

**Comment by chmorgan** [comment]
Bah. No idea what might be up with it. Have you used appveyor enough to
know where I should look?

**Comment by kayoub5** [comment]
did you select "user" or "administrator" in appvoyer team config page?

did you configure the webhook provided by appvoyer for team sync in github?

**Comment by kayoub5** [comment]
maybe try to invite me by email instead of using github groups?

**Comment by chmorgan** [comment]
I did select 'user', and the web hook looks like its configured as the team didn't show up until I had done some additional step to provide access to appveyor.

User inherits admin permissions, which means users can run, view etc, everything admin can do. Invited you using email address just a minute ago. Lmk if this opens up the proper permissions.

**Comment by kayoub5** [comment]
I got the invitation, but my account is still limited access wise, I can only see logs and download artifacts, nothing more. I think "User" is the wrong role since "Inherited" will grant me nothing if I don't belong to a role with higher access.

**Comment by kayoub5** [comment]
maybe create a new "Maintainer" role with more access than "User" ?

**Comment by chmorgan** [comment]
alright, added maintainers with more permissions, you are correct that user has literally nothing checked off, and reassigned the GitHub team to maintainer. Can you check that? I was hoping to avoid needing per-user permissions when we have the GitHub team.

**Comment by kayoub5** [comment]
What access did you add? because I don't see any changes.

**Comment by chmorgan** [comment]
![image](https://github.com/dotpcap/sharppcap/assets/1211904/8cb2768f-0cb2-4dee-b6e7-4ec5c5a78774)


![image](https://github.com/dotpcap/sharppcap/assets/1211904/729fa073-4a74-49d7-8a7c-3f34eabe6525)

**Comment by chmorgan** [comment]
Are you logging in with your GitHub account or your email address?

**Comment by kayoub5** [comment]
> Are you logging in with your GitHub account or your email address?

GitHub

**Comment by chmorgan** [comment]
Added 'maintainer' to your live email address too. Odd man.

**Comment by kayoub5** [comment]
now works

**Comment by chmorgan** [comment]
No idea. I did hit the 'sync permissions with github' button when I updated the team to maintainer, maybe it didn't sync yet/correctly? Should I remove access to the live account so we can test or just keep this?

**Comment by kayoub5** [comment]
fine by me to test again, if still doesn't not work, maybe drop a message to support.

**Comment by chmorgan** [comment]
Alright, removed your live user, let me know if things are still broken after you log in from GitHub.

**Comment by kayoub5** [comment]
Now your account does not even show up in the account drop down for me.

**Comment by chmorgan** [comment]
Alright, re-added as a user.

**Comment by kayoub5** [comment]
> @kayoub5 I saw dotnet approved appveyor integration. I didn't see a prompt or question about that here but maybe because I wasn't set as the organization in GitHub? Did you approve that?

@PhyxionNL reviewed and approved it.

**Comment by chmorgan** [comment]
Ahh k. Maybe things will work correctly now without your separate account? heh

**Comment by kayoub5** [comment]
it's the same account (same email and logged through GitHub button), it's just that appveyor is not detecting GitHub groups correctly.
