### ISSUE TITLE
How to use as Worker Service in .net 6.0

### ISSUE THREAD

**Issue by j-ghadiri** [dotpcap/sharppcap#397]
How to use this plugin for device capture  
`device.StartCapture();`
without use
`Console.ReadLine();`

or how to use this plugin for packet capture in windows service that create as [worker](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service) ???

in usual state not capture without Console.ReadLine() code and raise Device_OnCaptureStopped event ...

also I would capture device and collect to database...

**Comment by kayoub5** [comment]
`Console.ReadLine` is not required, it's just there to make the example console application wait for user input.

**Comment by j-ghadiri** [comment]
without `Console.ReadLine` capture stoped in worker service and raise Device_OnCaptureStopped event

**Comment by kayoub5** [comment]
You can use `Thread.Sleep(Timeout.Infinite);` instead.
