### ISSUE TITLE
Support for USBPcap devices

### ISSUE THREAD

**Issue by Dunnymeister** [dotpcap/sharppcap#410]
I was looking at porting some code from golang to c# and am stuck trying to get SharpPcap to return USBPcap devices. 

[gopacket](https://github.com/google/gopacket) returns them without doing anything special, provided that WinPcap and USBPcap is installed on the machine. Is there something I'm missing in SharpPcap or is it not supported currently?

**Comment by kayoub5** [comment]
Sharppcap does not currently support USBPcap

**Comment by Dunnymeister** [comment]
Thanks for the quick response and clarification 🙂

**Comment by chmorgan** [comment]
We’d be open to contributions to support this library, @kayoub5 ?

**Comment by kayoub5** [comment]
> We’d be open to contributions to support this library, @kayoub5 ?

yes
