### ISSUE TITLE
Support pcap_open without credentials for rpcap remote capturing

### ISSUE THREAD

**Issue by rexlManu** [dotpcap/sharppcap#411]
Hey,

I'm currently trying to remotly read windows traffic via rpcapd running on windows and reading it on Linux.

I compiled libpcap and tcpdump to support remote capture and I can see my windows traffic when I try to read it via tcpdump.

But to work I need to replace the backslash for doubles. as example: 
`tcpdump -i rpcap://192.168.2.115:1337/\\Device\\NPF_{D55DEB80-AD97-4004-9F0C-FD5661D9FC45}`

I tried to replicate this functionality with sharppcap but I always receive NoSuchDevice. The name is the same like above, only with the difference that its only single back slashes.

I don't know if thats a issue from here or libpcap directly.

My code (I don't think its important in this case but I just post it):
```csharp
 var remoteInterfaces = PcapInterface.GetAllPcapInterfaces("rpcap://192.168.2.115:1337/", null);
 var interface = remoteInterfaces[0];
 var device = new LibPcapLiveDevice(interface);
 device.Open(new DeviceConfiguration {ReadTimeout = 500, Mode = DeviceModes.None}); // error occuries while activating on cpad
```

**Comment by kayoub5** [comment]
Npcap/WinPcap version used in client/server?

**Comment by kayoub5** [comment]
Use `new RemoteAuthentication(AuthenticationTypes.Null, null, null)` instead of `null`

**Comment by rexlManu** [comment]
That's a good work around.
