### ISSUE TITLE
Error while loading SharpPcap dll in LabVIEW on Windows 7

### ISSUE THREAD

**Issue by CyrilFRA** [dotpcap/sharppcap#417]
Hello,
 
I’m creating a LabVIEW library to capture the network. It uses SharpPcap to connect to nPcap. I got compiled dll with dependencies from [NuGets](http://www.nuget.org/).
I made my development on Windows 10 x64, **everything is working well**.

I need to install it on an offline **Windows 7 x64** PC. 
I don’t know why, but SharpPcap dll could not be loaded by LabVIEW (2017 x64)…
![LV_Error](https://user-images.githubusercontent.com/113695670/190646569-26927447-2907-4799-9eec-d87586c70ab0.PNG)

However npcap 1.6 is installed (after installing updates to handle driver signatures), Wireshark runs fine and Microsoft .Net framework 4.6.2 is installed.

I scan shappcap.dll on [Dependencies Walker](https://github.com/lucasg/Dependencies) (2 differents versions, screenshots attached). 
It seems to have problems with the following: netstandard, libc, ndisapi.dll with the last version, and gpsvc.dll and ieshims.dll on an old version of Dependency walker.
![Capture_Dependencies](https://user-images.githubusercontent.com/113695670/190646614-d161f132-0b47-4aa4-81cb-d0f656e26b0f.PNG)
![Capture_Dependency Walker](https://user-images.githubusercontent.com/113695670/190646624-3084c3a8-5824-40ef-9b21-29a2943f66f6.PNG)

Do you have an idea where the problem come from ? Do I have to install another framework ? Or Windows 7 is unable to run SharpPcap?
 
Here is my installed programs if it can help :
![Programmes](https://user-images.githubusercontent.com/113695670/190646871-19835cd2-d443-467b-a114-45893688fac6.png)

Best Regards

**Comment by kayoub5** [comment]
Try upgrading the project to target .NET Framework 4.7.2 or higher.
See https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

**Comment by kayoub5** [comment]
.NET Standard 2.0 was released August 14th, 2017, so it could be that LabVIEW 2017 is using an outdated .NET version that do not support .NET Standard 2.0
