### ISSUE TITLE
How to read voip information

### ISSUE THREAD

**Issue by suzhou-Second** [dotpcap/sharppcap#426]
I want to read the information in the RTP package, but I don't know how to read it. 
Whether RTP can be read

**Comment by kayoub5** [comment]
See example in https://github.com/dotpcap/packetnet/blob/af442b608f72d0c3f19ed4a9dc32f950558fde48/Test/PacketType/RtpPacketTest.cs

For RTP and packet dissection in general please use https://github.com/dotpcap/packetnet repo.
