### ISSUE TITLE
How to capture and parse HTTP protocol packets

### ISSUE THREAD

**Issue by Shadow-XT** [dotpcap/sharppcap#432]
Because of the needs of the program, I want to know how to capture the HTTP protocol packets through SharpPcap. Because in SharpPcap, I only found the transport layer protocols such as TCP and UDP, but the upper application layer protocols were not found. If the application layer protocol interface is not provided, what programming methods can capture and parse the application layer protocols?

**Comment by kayoub5** [comment]
See https://github.com/dotpcap/packetnet-connections/blob/master/Examples/HttpMonitorExample/Main.cs
