### ISSUE TITLE
Unable to load DLL 'wpcap' or one of its dependencies

### ISSUE THREAD

**Issue by vikofun** [dotpcap/sharppcap#447]
I am using the latest version. Why are there errors?

System.DllNotFoundException:“Unable to load DLL 'wpcap' or one of its dependencies: The specified module cannot be found. (0x8007007E)”

![123](https://user-images.githubusercontent.com/50802038/216340614-2e509a8a-5e6e-48b1-91c2-199fb119a24e.png)
![234](https://user-images.githubusercontent.com/50802038/216340623-57c308f0-3aa8-4843-a953-a076832b5527.png)

**Comment by kayoub5** [comment]
Simply put, it means WinPcap or Npcap are not installed on the system.

**Comment by vikofun** [comment]
I use windows11, which requires me to manually install WinPcap or Npcap?

**Comment by kayoub5** [comment]
> I use windows11, which requires me to manually install WinPcap or Npcap?

you need to install it manually, it doesn't matter what version of windows you are using
