### ISSUE TITLE
IPv4 Length exceeds Packet Length during live device capture

### ISSUE THREAD

**Issue by exp111** [dotpcap/sharppcap#449]
I've encountered this issue where I can't access the tcp payload data during a live recording with SharpPcap and PacketDotNet.
Looked into it a bit deeper and found out that during live recording the fragmented packets have the wrong length.
Attached is a pcap that I created using the CaptureFileWriterDevice as wireshark didn't produce faulty packets.

[pcap.zip](https://github.com/dotpcap/sharppcap/files/10969073/pcap.zip)
The packet in question:
![grafik](https://user-images.githubusercontent.com/17885980/225016246-a91bb3ee-f217-49e6-b6a6-d228e26b2e0e.png)
Image of the packet recorded using wireshark (not the same recording):
![grafik](https://user-images.githubusercontent.com/17885980/225015848-1a685dfe-0b99-4f3d-bb25-959531edd50d.png)

Maybe it's because I'm capturing the loopback device? Is this a bug in sharpcap or is it the driver?

Using Windows 10, SharpPcap 6.2.5, Npcap 1.72
Also tried using the CreatingCaptureFile example with the same result.

**Comment by kayoub5** [comment]
increase DeviceConfiguration.Snaplen

**Comment by exp111** [comment]
That fixed it, thanks
