### ISSUE TITLE
Libpcap 1.10+ rfmon not supported

### ISSUE THREAD

**Issue by LynxOfTheSky** [dotpcap/sharppcap#457]
Good day to you, sir.

I recently started using sharpcap 6.2.5 on kali-linux, and tried to open wi-fi adapter (alfa awus 1900) in monitor mode with next code:

var configuration = new DeviceConfiguration()
{
    Mode = DeviceModes.Promiscuous,
    ReadTimeout = readTimeoutMilliseconds,
    Monitor = MonitorMode.Active
};
testDevice.Open(configuration);

On libpcap 10+ it returns "SharpPcap.PcapException: Unable to activate the adapter (wlan0). (Error Code: RfmonNotSupported)",
which is a reported issue of libpcap, like here: https://github.com/bettercap/bettercap/issues/819
Their solution was just reverting to libpcap 9.1.4, which i did, but than the same code from above returns another error: SharpPcap.PcapException: Unable to activate the adapter (wlan0). (Error Code: Generic).

The adapter switches to monitor fine, and if i switch it manually and then open the testDevice without monitor mode mentioned - it captures packets just fine, but that adds some steps to using the program.

Could you please add the back-compatibility with older libpcap versions, or help me with which version of sharppcap supported libpcap 1.9.1.4?

ADDED:
on libpcap 1.9.1.4 if i remove the monitor setting:
var configuration = new DeviceConfiguration()
{
    Mode = DeviceModes.Promiscuous,
    ReadTimeout = readTimeoutMilliseconds
};
testDevice.Open(configuration);

no error is raised. So the problem is that monitor setting is not compatible with libpcap 9-. But the libpcap 10+ does not support monitor mode itself.

**Comment by kayoub5** [comment]
@LynxOfTheSky sharppcap is only a wrapper for libpcap, the error you got is most likely coming from libpcap itself.

Usually support for Monitor mode depends on the adapter and its driver, if the driver says "no monitor mode supported", there isn't much that can be done about it. 

PS: when reporting error ALWAYS include the full stack trace and error message.
