### ISSUE TITLE
Unable to get libpcap (and by extension sharppcap) to work on Ubuntu 20.04

### ISSUE THREAD

**Issue by mkinalamscreen** [dotpcap/sharppcap#468]
Good evening,

I've been using SharpPcap (via Npcap) for packet capture on Windows and have been compiling it in .NET 7, however, when publishing to a project to Linux, I have been incapable of getting the application to pass SharpPcap's version compatibility check. The issue I have gotten persists whether I used libpcap-dev, or libpcap0.8. I have checked /usr/lib/x86_64_linux_gnu/ for libpcap.so.0.8 and libpcap-dev and can confirm that I have both installed.

![image](https://github.com/dotpcap/sharppcap/assets/140155898/0054081e-7a63-4f88-a994-b0c703e85883)

Upon dissecting the Windows version, I have noticed that the version information is being passed through Npcap. I am unsure whether or not I am properly including all the necessary library files required to run SharpPcap, even when I install the respective libpcap libraries for Linux. 

![image](https://github.com/dotpcap/sharppcap/assets/140155898/1154bede-48c8-4c75-a70d-a98e32cd9f35)

It should be noted that the app I am trying to deploy on Linux utilises SharpPcap as a nuget package, and the screenshot above comes from the SharpPcap github clone itself. Trying to deploy either my app or an existing example from the SharpPcap repo onto Linux has resulted in the same issue.

Could anyone please tell me where I have gone wrong in the installation process for libpcap?

Thanks

**Comment by kayoub5** [comment]
* libpcap version that you installed in Linux?
* are you using sudo/root?

**Comment by mkinalamscreen** [comment]
Hi, I'm using version 1.9.1-3 for libpcap0.8

I'm executing the dotnet app with sudo. I've tried publishing both Linux x86 and portable files and have gotten the same result.

**Comment by kayoub5** [comment]
from exception, it seems your wifi adapter does not support promiscuous mode, so you need to change the mode in the `Open` function

**Comment by mkinalamscreen** [comment]
![image](https://github.com/dotpcap/sharppcap/assets/140155898/1075e64c-e80d-40fa-97ce-f63588348c1e)

I've just tried it now, same error. All of my interfaces were set with promiscuous mode turned off. I also tried a different interface but it resulted in the same exception.

**Comment by kayoub5** [comment]
does  tcpdump work on that interface?

**Comment by mkinalamscreen** [comment]
I've just installed tcpdump and ran sudo tcpdump -i wwan0, it returned raw packages:

![image](https://github.com/dotpcap/sharppcap/assets/140155898/832af880-6234-4457-ab01-2f5cc0733f26)

I tried executing the CreateCaptureFile program on lo and any interfaces, same issue.

I have removed the promiscuous mode from the open function

![image](https://github.com/dotpcap/sharppcap/assets/140155898/97afc8a1-2d86-48c5-ae7e-db274e0aa4d9)

**Comment by kayoub5** [comment]
Ok, remove all other modes, put promiscuous back.
libpcap/sharppcap is complaining about lack of support for NoCaptureLocal and DataTransferUdp
