### ISSUE TITLE
Timeval unchanged between captured packets in Example03

### ISSUE THREAD

**Issue by FlightlessKiwi** [dotpcap/sharppcap#470]
Running the sample always returns the same time stamp 19:36:25,868, even between invocations. Is it a bug?

**Comment by kayoub5** [comment]
Timestamp comes from PCAP library
What Libpcap / Npcap version do you have installed?

**Comment by kayoub5** [comment]
Possibly caused by https://github.com/nmap/npcap/issues/668, upgrade to latest Npcap if that's the case

**Comment by FlightlessKiwi** [comment]
The Npcap that was installed on my windows 11 is 1.74. I notice that there
is now a 1.76. I'll try to upgrade it and report back if that solves the
problem.

**Comment by FlightlessKiwi** [comment]
Npcap 1.76 fixes the issue. Thanks.
