### ISSUE TITLE
Integration request. Are you interested?

### ISSUE THREAD

**Issue by buldo** [dotpcap/sharppcap#475]
Hello  
I ported RTL8812AU linux driver to .NET.  
Now it supports only monitor mode on Windows and Android. But I plan to provide injection support too.  

If your interested in providing monitor/injection support via this driver, let me know and say what should I do for integration with sharppcap.

Driver repo: https://github.com/buldo/WiFiDriver.git

**Comment by kayoub5** [comment]
Contributions are welcome in general, but two things to keep in mind:
* The integration needs to be testable on a CI
* The contribution needs to be under the LGPL license, not GPL license.

**Comment by buldo** [comment]
Original driver has Gplv2 license. I'm not shure is it possible to do integration under lgpl.

Also have no idea how to test device driver on CI.

Now I think that is better idea ia show how to use packetNet for parsing my driver output in driver readme
