### ISSUE TITLE
Unable to load DLL 'wpcap'

### ISSUE THREAD

**Issue by MFarfan402** [dotpcap/sharppcap#477]
Hi!

Taking as reference previous closed issue: https://github.com/dotpcap/sharppcap/issues/447

Got into same issue. I'm not allowed to install WinPcap or Npcap. Is there a workaround that I could try? 

I'm able to obtain wpcap.dll but not able to dynamically load into program. Any suggestion I can try?

**Comment by kayoub5** [comment]
Npcap is a driver, you can't just copy the dll and it works.

Without context on why you are not allowed to install the drivers, it's difficult to suggest alternatives.

SharpPcap is a driver wrapper, you are asking for an eggless omelette.

**Comment by KyleC69** [comment]
Is there a list of pre-reqs posted? Not seeing any requirements listed on readme.

**Comment by kayoub5** [comment]
From README:
<img width="522" height="156" alt="Image" src="https://github.com/user-attachments/assets/c9e58268-699c-4ba1-a4f9-d0b7fa499fd3" />

**Comment by KyleC69** [comment]
I did finally figure it out. Not to sound like i'm nit picking  but it says 'support for' not that it is required. Thank you for your reply.


________________________________
