### ISSUE TITLE
CaptureFileWriterDevice.Write((RawCapture p) ignores PacketLength field

### ISSUE THREAD

**Issue by alikovvl** [dotpcap/sharppcap#479]
If the data buffer is larger than the packet, it will be completely saved in a pcap file. This results in a large pcap file and makes it difficult to analyze. Such buffers are obtained by using ArrayPool.Rent.

**Comment by kayoub5** [comment]
got an example?

**Comment by alikovvl** [comment]
https://github.com/dotpcap/sharppcap/blob/b6a0533200400c6b80377067286e7c6c221d2c2b/SharpPcap/LibPcap/CaptureFileWriterDevice.cs#L202

This will happen if the buffer size is not equal to the packet size.

**Comment by kayoub5** [comment]
you need to create `Span<byte>` with correct size from the array you rented.

**Comment by alikovvl** [comment]
[Sharppcap.Issue479.zip](https://github.com/dotpcap/sharppcap/files/13201633/Sharppcap.Issue479.zip)
