### ISSUE TITLE
SharpPcap is not trimmable because of dependency on NativeLibrary.SetDllImportResolver

### ISSUE THREAD

**Issue by landerverhacklansweeper** [dotpcap/sharppcap#517]
I recently got an issue using SharpPcap 9.0.0 on linux-x64 (.NET 8.0). It would not load correctly until I turned off Trimming during publish.
The culprit is the following class: [NativeLibraryHelper](https://github.com/dotpcap/sharppcap/blob/master/SharpPcap/LibPcap/NativeLibraryHelper.cs).

For some reason, it uses reflection to get the `SetDllImportResolver` method of the `NativeLibrary` class in `System.Runtime.InteropServices`. Because of this, the compiler is unaware of this dependency. 
Can we add something like 
```cs
[DynamicDependency(DynamicallyAccessedMemberTypes.PublicMethods, typeof(NativeLibrary))]
public static void SetDllImportResolver(Assembly assembly, DllImportResolver resolver)
{
    // existing code
}
```
So the trimming would not throw out this required method?

I added this to my own method, and it does seem to work.

I have no idea why `NativeLibraryHelper` uses reflection, but whatever the reason, it might also be the reason why this attribute might not be set.

Could we avoid the reflection all together? It also hinders my plan to use AOT. I want to be able to run on weaker hardware.

**Comment by kayoub5** [comment]
The problem could be fixed by writing the same logic without reflection inside a `#if NET6_0_OR_GREATER`, while keeping the old logic for backward compatibility in the `#else` block, then compiling the library for both .NET standard, .NET 6 and 8

PR welcome if someone wants to take a swing at this.
