### ISSUE TITLE
ShapPcap cannot handle virtual interfaces with 16 byte hardware addresses

### ISSUE THREAD

**Issue by landerverhacklansweeper** [dotpcap/sharppcap#518]
I came across this issue when using a device that has a virtual interface for tunneling. The hardware address is `00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00`. This causes issues in the `Sockaddr` class since the buffer provided is only 8 bytes in length.

I don't know what to make of this. Should we ignore such interfaces? should we just trim it, to hold just 8 bytes? the hardware address doesn't seem to be useful anyway.

What is certain, is that SharpPcap chrashes when such a device interface is present.

**Comment by kayoub5** [comment]
@landerverhacklansweeper a PR is welcome

Question: what type does the socket address have?

**Comment by landerverhacklansweeper** [comment]
I added this code in the `SockAddr` constructor
```cs
Console.WriteLine($"Sockaddr ctor sll_addr length:{saddr_ll.sll_addr.Length} hwAddrBytes length:{hwAddrBytes.Length}");
if (hwAddrBytes.Length > 6)
{
    Console.WriteLine($"type {saddr_ll.sll_hatype}");
    Console.WriteLine($"protocol {saddr_ll.sll_protocol}");
    Console.WriteLine($"ifindex {saddr_ll.sll_ifindex}");
    Console.WriteLine($"pkttype {saddr_ll.sll_pkttype}");
    Console.WriteLine($"family {saddr_ll.sll_family}");
}
```

result:
```
Sockaddr ctor sll_addr length:8 hwAddrBytes length:16
type 769
protocol 0
ifindex 5
pkttype 0
family 17
```

**Comment by kayoub5** [comment]
@landerverhacklansweeper what actual error are you getting in the crash? could you provide the stack trace ?

Is this happening in Windows or Linux?

**Comment by landerverhacklansweeper** [comment]
The error occurs in Linux (a proprietary version of Red Hat, ARM64).
The exact location is [here](https://github.com/dotpcap/sharppcap/blob/f660b4231880e63aa801ca0f55175abc14e8616f/SharpPcap/LibPcap/Sockaddr.cs#L101). 

```cs
Buffer.BlockCopy(saddr_ll.sll_addr, 0, hwAddrBytes, 0, hwAddrBytes.Length);
```
Causes an out of range exception, since `hwAddrBytes.Length` is 16 while `saddr_ll.sll_addr` is a `byte[]` with length 8. (see [PcapUnmanagedStructures](https://github.com/dotpcap/sharppcap/blob/f660b4231880e63aa801ca0f55175abc14e8616f/SharpPcap/LibPcap/PcapUnmanagedStructures.cs#L117)) 

If you still want the exact stacktrace, I can provide it to you once I get my hands on the same device. 

Currently I circumvented the problem by adding 
```cs
Buffer.BlockCopy(saddr_ll.sll_addr, 0, hwAddrBytes, 0, Math.Min(hwAddrBytes.Length,8));
```
Since the address is non-sensical anyway.

**Comment by kayoub5** [comment]
@landerverhacklansweeper Please open a PR with the fix, I can't reproduce this locally.

The root cause as far as I see is that sockaddr_ll have 8 bytes in sll_addr according to Linux https://man7.org/linux/man-pages/man7/packet.7.html

Could you provide what sockaddr_ll looks like in your system?

Also the values of AF_INET, AF_INET6 and AF_PACKET?

**Comment by landerverhacklansweeper** [comment]
Hey, I used the following code in the `SocketAddr` constructor:

```cs
var saddr_ll = Marshal.PtrToStructure<sockaddr_ll>(sockaddrPtr);
Console.WriteLine($"addr {BitConverter.ToString(saddr_ll.sll_addr)}");
Console.WriteLine($"halen {saddr_ll.sll_halen}");
Console.WriteLine($"type {saddr_ll.sll_hatype}");
Console.WriteLine($"protocol {saddr_ll.sll_protocol}");
Console.WriteLine($"ifindex {saddr_ll.sll_ifindex}");
Console.WriteLine($"pkttype {saddr_ll.sll_pkttype}");
Console.WriteLine($"family {saddr_ll.sll_family}");

Console.WriteLine($"AF_INET {Pcap.AF_INET}");
Console.WriteLine($"AF_INET {Pcap.AF_INET6}");
Console.WriteLine($"AF_INET {Pcap.AF_PACKET}");
```

with the following result:

```
addr 00-00-00-00-00-00-00-00
halen 16
type 769
protocol 0
ifindex 5
pkttype 0
family 17
AF_INET 2
AF_INET 10
AF_INET 17
```

So it seems I was wrong before, the hardware address is not `00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00`. It's just 8 bytes. but the length is 16. That's why I had an empty byte[] of 16 bytes before. 
So why would `halen` be `16`?

**Comment by kayoub5** [comment]
you need to fork to create PR

I need values of AF_INET, AF_INET6 and AF_PACKET from your OS Linux C headers, not from C#

same for saddr_ll, what it looks like in the C headers of your OS.

**Comment by landerverhacklansweeper** [comment]
I'm struggling a bit here since I usually don't work on Linux,
The OS that I'm running doesn't have these values. I don't even have a `usr/include` directory.
I assume these values come from the OS I'm building on. But I'm currently compiling it on Windows (non-AoT).

**Comment by kayoub5** [comment]
That's the main issue, AF_INET, AF_INET6 and AF_PACKET have different values depending on OS

An address of 16 bytes, sounds like an IPv6 address, not a MAC Address

I worry that (for example) you compiled something with Windows headers, and got some macro values mangled up

For include directory, check `/usr/lib/gcc/`, also see https://stackoverflow.com/questions/4980819/what-are-the-gcc-default-include-directories

**Comment by kayoub5** [comment]
Another possible reason for the issue, is the fact that you are using ARM64, none of the maintainers have access to ARM64 devices.

**Comment by landerverhacklansweeper** [comment]
> I worry that (for example) you compiled something with Windows headers, and got some macro values mangled up
I don't think so, because all the other interfaces seem ok.

It's more likely that it's just a weird device. It's a networking device, a kind of firewall.

Here is the output of `ip link show`. The problematic one is number 5. It does not appear when I use `ifconfig` 
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 2048
    link/ether 00:1c:7f:b6:68:61 brd ff:ff:ff:ff:ff:ff
3: DMZ: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 2048
    link/ether 00:1c:7f:b6:68:62 brd ff:ff:ff:ff:ff:ff
4: WAN: <NO-CARRIER,BROADCAST,MULTICAST,DYNAMIC,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 2048
    link/ether 00:1c:7f:b6:68:60 brd ff:ff:ff:ff:ff:ff
5: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd ::
6: LAN1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:1c:7f:b6:68:61 brd ff:ff:ff:ff:ff:ff
7: LAN2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:1c:7f:b6:68:61 brd ff:ff:ff:ff:ff:ff
8: LAN3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:1c:7f:b6:68:61 brd ff:ff:ff:ff:ff:ff
9: LAN4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:1c:7f:b6:68:61 brd ff:ff:ff:ff:ff:ff
```
Thanks for all the help so far.
