### ISSUE TITLE
ipv6 packets could not be parsed

### ISSUE THREAD

**Issue by jeowill-zhou** [dotpcap/sharppcap#519]
[pp2.zip](https://github.com/user-attachments/files/16269688/pp2.zip)

it looks abnormal when using ipv6 packets

        private void Reader_OnPacketArrival(object sender, PacketCapture e)
        {

                if (rawpacket.LinkLayerType != LinkLayers.Ethernet)
                {
                    return null;
                }

                var packetLength = rawpacket.Data.Length;
                var ethPacket = Packet.ParsePacket(rawpacket.LinkLayerType, rawpacket.Data) as EthernetPacket;
                var ipPacket = ethPacket.Extract<IPPacket>();

               //ipPacket.Protocol is 0x09  which not in enum values
              // I cannot convert the ipPacket to IPv6Packets

        }

**Comment by jeowill-zhou** [comment]
CaptureFileReaderDevice reader = new CaptureFileReaderDevice("d:\\pp2.pcap");
       reader.OnPacketArrival += Reader_OnPacketArrival;
       reader.Open();
       reader.Filter = "";
       reader.Capture();
       reader.Close();

**Comment by kayoub5** [comment]
@jeowill-zhou how did you generate this traffic?

It has bogus Ethernet header

![image](https://github.com/user-attachments/assets/44892d23-f2a5-4fef-931d-8ddc7c0c4fc6)

**Comment by kayoub5** [comment]
No feedback, closing.

@PhyxionNL up to you if you want to support those broken packets that use the wrong EtherType.

Wireshark seems to support them at least.
