### ISSUE TITLE
SharpPcap.PcapException:“expression rejects all packets”

### ISSUE THREAD

**Issue by xljiulang** [dotpcap/sharppcap#529]
```
 device.Filter = "ip6 and (tcp[tcpflags] & tcp-syn == tcp-syn)";
```

**Comment by kayoub5** [comment]
Stack trace?

**Comment by kayoub5** [comment]
@xljiulang The error is coming from Lippcap itself
See https://github.com/the-tcpdump-group/libpcap/blob/afa58de01aba5b7f971b1f8d72a1fc5b5fd514e4/gencode.c#L848

If you think it's incorrect, please report it to https://github.com/the-tcpdump-group/libpcap
