### ISSUE TITLE
'Unable to load shared library 'wpcap''  in linux container

### ISSUE THREAD

**Issue by ChrisZ32** [dotpcap/sharppcap#543]
Trying to use this library in a linux docker container but even with the most basic test app I get the exception "System.DllNotFoundException: 'Unable to load shared library 'wpcap' or one of its dependencies". If I run the raw console app on my windows PC it works fine, its when running the linux container I get this.

I am unfamiliar with the libraries involved here to be honest, but my understanding is SharpPcap is supposed to wrap around wpcap when running on windows and libpcap when running on linux? So why is it trying to load wpcap?

Any pointers appreciated as I've run out of ideas!

The very minimal test app:

[BasicTestApp.zip](https://github.com/user-attachments/files/17722566/BasicTestApp.zip)

Stacktrace:  

System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load shared library 'wpcap' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/wpcap.so: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/wpcap.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libwpcap.so: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/libwpcap.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/wpcap: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/wpcap: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libwpcap: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/libwpcap: cannot open shared object file: No such file or directory

  Source=SharpPcap
  StackTrace:
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)
   at SharpPcap.LibPcap.PcapInterface.GetAllPcapInterfaces()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList..ctor()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance()
   at SharpPcap.CaptureDeviceList..ctor()
   at SharpPcap.CaptureDeviceList.get_Instance()
   at ConsoleApp1.Program.Main(String[] args) in C:\Projects\ConsoleApp1\Program.cs:line 9

**Comment by kayoub5** [comment]
need more details, did you install libpcap? if yes, how?

Linux distro? version?

**Comment by ChrisZ32** [comment]
Thought I had checked libpcap was installed but obviously it wasn't. Once installed, works fine. Thanks for the pointer to check!

Guess I was thrown by the error message mentioning wpcap so I was going down the wrong path of thinking it was trying to load the wrong library. As a newbie to the library, I would recommend a more descriptive (accurate?) error message, but will close this as not an issue.

Thanks!

**Comment by kayoub5** [comment]
The error message is coming from .NET itself, the current implementation uses `wpcap` as main library name, for backward compatibility with .NET Framework , and configure an alias for .NET 8 in Linux/macos at runtime.
